@url = http://localhost:5173

GET {{url}}/expenses

###

GET {{url}}/expenses/6

###

POST {{url}}/expenses
content-type: application/json

{
  "name": "New name",
  "amount": 10.2
}

###

DELETE {{url}}/expenses/6