packages:
  - apps/*
  - packages/*

catalog:
  '@eslint/js': ^9.37.0
  '@hono/node-server': ^1.19.5
  '@hono/vite-build': ^1.7.0
  '@hono/vite-dev-server': ^0.22.0
  '@hono/zod-validator': ^0.7.3
  '@neondatabase/serverless': ^1.0.2
  '@tailwindcss/vite': ^4.1.14
  '@types/node': ^22.18.8
  '@types/pg': ^8.15.5
  '@types/react': 19.2.2
  '@types/react-dom': 19.2.1
  '@tanstack/react-query': ^5.90.2
  '@tanstack/react-router': ^1.132.47
  '@tanstack/router-plugin': ^1.132.47
  '@tanstack/react-query-devtools': ^5.90.2
  '@tanstack/react-router-devtools': ^1.132.50
  '@vercel/analytics': ^1.5.0
  '@vercel/speed-insights': ^1.2.0
  '@vitejs/plugin-react': ^5.0.4
  autoprefixer: ^10.4.21
  clsx: ^2.1.1
  class-variance-authority: ^0.7.1
  dayjs: ^1.11.18
  drizzle-kit: ^0.31.5
  drizzle-orm: ^0.44.6
  eslint: ^9.37.0
  eslint-config-prettier: ^10.1.8
  eslint-plugin-import: ^2.32.0
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-prettier: ^5.5.4
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^6.1.1
  eslint-plugin-react-refresh: ^0.4.23
  eslint-plugin-turbo: ^2.5.8
  eslint-plugin-unused-imports: ^4.2.0
  globals: ^16.4.0
  hono: ^4.9.10
  husky: ^9.1.7
  lint-staged: ^16.2.3
  lucide-react: ^0.545.0
  pg: ^8.16.3
  prettier: ^3.6.2
  prettier-eslint: ^16.4.2
  prettier-plugin-tailwindcss: ^0.6.14
  react: ^19.2.0
  react-dom: ^19.2.0
  sonner: ^2.0.7
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.14
  tw-animate-css: ^1.4.0
  typescript: 5.9.3
  typescript-eslint: ^8.46.0
  vite: ^7.1.9
  vite-tsconfig-paths: ^5.1.4
  zod: ^4.1.12

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - '@vercel/speed-insights'
  - better-sqlite3
  - esbuild
  - sharp
  - workerd
