packages:
  - apps/*
  - packages/*

catalog:
  '@eslint/js': ^9.38.0
  '@hono/node-server': ^1.19.5
  '@hono/zod-validator': ^0.7.4
  '@hookform/resolvers': ^5.2.2
  '@neondatabase/serverless': ^1.0.2
  '@radix-ui/react-avatar': ^1.1.10
  '@radix-ui/react-checkbox': ^1.3.3
  '@radix-ui/react-dialog': ^1.1.15
  '@radix-ui/react-dropdown-menu': ^2.1.16
  '@radix-ui/react-label': ^2.1.7
  '@radix-ui/react-select': ^2.2.6
  '@radix-ui/react-separator': 1.1.7
  '@radix-ui/react-slot': 1.2.3
  '@radix-ui/react-tabs': ^1.1.13
  '@radix-ui/react-tooltip': ^1.2.8
  '@react-email/components': ^0.5.7
  '@react-email/preview-server': ^4.3.1
  '@react-email/tailwind': ^1.2.2
  '@tailwindcss/vite': ^4.1.15
  '@tanstack/react-query': ^5.90.5
  '@tanstack/react-query-devtools': ^5.90.2
  '@tanstack/react-router': ^1.133.22
  '@tanstack/react-router-devtools': ^1.133.22
  '@tanstack/react-table': ^8.21.3
  '@tanstack/router-plugin': ^1.133.22
  '@types/node': ^22.18.12
  '@types/pg': ^8.15.5
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.2
  '@vercel/analytics': ^1.5.0
  '@vercel/speed-insights': ^1.2.0
  '@vitejs/plugin-react': ^5.0.4
  autoprefixer: ^10.4.21
  better-auth: ^1.3.28
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  dayjs: ^1.11.18
  dotenv: ^17.2.3
  drizzle-kit: ^0.31.5
  drizzle-orm: ^0.44.6
  drizzle-zod: ^0.8.3
  eslint: ^9.38.0
  eslint-config-prettier: ^10.1.8
  eslint-plugin-import: ^2.32.0
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-prettier: ^5.5.4
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^7.0.0
  eslint-plugin-react-refresh: ^0.4.24
  eslint-plugin-turbo: ^2.5.8
  eslint-plugin-unused-imports: ^4.3.0
  globals: ^16.4.0
  hono: ^4.10.2
  husky: ^9.1.7
  lint-staged: ^16.2.5
  lucide-react: 0.546.0
  pg: ^8.16.3
  prettier: ^3.6.2
  prettier-eslint: ^16.4.2
  prettier-plugin-tailwindcss: ^0.7.1
  react: ^19.2.0
  react-dom: ^19.2.0
  react-email: ^4.3.1
  react-hook-form: ^7.65.0
  resend: ^6.2.2
  sonner: ^2.0.7
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.15
  tsc-alias: ^1.8.16
  tsx: ^4.20.6
  tw-animate-css: ^1.4.0
  typescript: 5.9.3
  typescript-eslint: ^8.46.2
  vite: ^7.1.11
  vite-tsconfig-paths: ^5.1.4
  zod: ^4.1.12

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - '@vercel/speed-insights'
  - better-sqlite3
  - esbuild
  - sharp
  - workerd
