packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@eslint/js": ^9.37.0
  "@types/node": ^22.18.8
  "@types/react-dom": 19.2.0
  "@types/react": 19.2.0
  "react-dom": ^19.2.0
  eslint-config-prettier: ^10.1.8
  eslint-plugin-import: ^2.32.0
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-prettier: ^5.5.4
  eslint-plugin-react-hooks: ^6.1.1
  eslint-plugin-react-refresh: ^0.4.23
  eslint-plugin-react: ^7.37.5
  eslint-plugin-turbo: ^2.5.8
  eslint-plugin-unused-imports: ^4.2.0
  eslint: ^9.37.0
  globals: ^16.4.0
  prettier-eslint: ^16.4.2
  prettier-plugin-tailwindcss: ^0.6.14
  prettier: ^3.6.2
  react: ^19.2.0
  typescript-eslint: ^8.45.0
  typescript: 5.9.3