/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AuthenticatedOnboardedRouteImport } from './routes/_authenticated/_onboarded'
import { Route as AuthenticatedJoinHouseholdRouteImport } from './routes/_authenticated/join-household'
import { Route as AuthenticatedOnboardingRouteRouteImport } from './routes/_authenticated/onboarding/route'
import { Route as AuthenticatedOnboardedIndexRouteImport } from './routes/_authenticated/_onboarded/index'
import { Route as AuthenticatedOnboardedUserProfileRouteImport } from './routes/_authenticated/_onboarded/user-profile'
import { Route as AuthenticatedOnboardingIndexRouteImport } from './routes/_authenticated/onboarding/index'
import { Route as AuthenticatedOnboardingCreateHouseholdRouteImport } from './routes/_authenticated/onboarding/create-household'
import { Route as AuthenticatedOnboardingInviteMembersRouteImport } from './routes/_authenticated/onboarding/invite-members'
import { Route as AuthenticatedOnboardedExpensesMonthlyExpensesRouteImport } from './routes/_authenticated/_onboarded/expenses/monthly-expenses'
import { Route as AuthenticatedOnboardedManageHouseholdMembersRouteImport } from './routes/_authenticated/_onboarded/manage/household-members'
import { Route as AuthenticatedOnboardedManageSettingsRouteImport } from './routes/_authenticated/_onboarded/manage/settings'
import { Route as AuthenticatedOnboardedFamilyKidsIndexRouteImport } from './routes/_authenticated/_onboarded/family/kids/index'
import { Route as AuthenticatedOnboardedFamilyKidsProfileIdRouteRouteImport } from './routes/_authenticated/_onboarded/family/kids/$profileId/route'
import { Route as AuthenticatedOnboardedFamilyKidsProfileIdIndexRouteImport } from './routes/_authenticated/_onboarded/family/kids/$profileId/index'
import { Route as AuthenticatedOnboardedFamilyKidsProfileIdDictionaryRouteImport } from './routes/_authenticated/_onboarded/family/kids/$profileId/dictionary'
import { Route as AuthenticatedOnboardedFamilyKidsProfileIdGeneralRouteImport } from './routes/_authenticated/_onboarded/family/kids/$profileId/general'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardedRoute = AuthenticatedOnboardedRouteImport.update({
  id: '/_onboarded',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJoinHouseholdRoute =
  AuthenticatedJoinHouseholdRouteImport.update({
    id: '/join-household',
    path: '/join-household',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardingRouteRoute =
  AuthenticatedOnboardingRouteRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardedIndexRoute =
  AuthenticatedOnboardedIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOnboardedRoute,
  } as any)
const AuthenticatedOnboardedUserProfileRoute =
  AuthenticatedOnboardedUserProfileRouteImport.update({
    id: '/user-profile',
    path: '/user-profile',
    getParentRoute: () => AuthenticatedOnboardedRoute,
  } as any)
const AuthenticatedOnboardingIndexRoute =
  AuthenticatedOnboardingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOnboardingRouteRoute,
  } as any)
const AuthenticatedOnboardingCreateHouseholdRoute =
  AuthenticatedOnboardingCreateHouseholdRouteImport.update({
    id: '/create-household',
    path: '/create-household',
    getParentRoute: () => AuthenticatedOnboardingRouteRoute,
  } as any)
const AuthenticatedOnboardingInviteMembersRoute =
  AuthenticatedOnboardingInviteMembersRouteImport.update({
    id: '/invite-members',
    path: '/invite-members',
    getParentRoute: () => AuthenticatedOnboardingRouteRoute,
  } as any)
const AuthenticatedOnboardedExpensesMonthlyExpensesRoute =
  AuthenticatedOnboardedExpensesMonthlyExpensesRouteImport.update({
    id: '/expenses/monthly-expenses',
    path: '/expenses/monthly-expenses',
    getParentRoute: () => AuthenticatedOnboardedRoute,
  } as any)
const AuthenticatedOnboardedManageHouseholdMembersRoute =
  AuthenticatedOnboardedManageHouseholdMembersRouteImport.update({
    id: '/manage/household-members',
    path: '/manage/household-members',
    getParentRoute: () => AuthenticatedOnboardedRoute,
  } as any)
const AuthenticatedOnboardedManageSettingsRoute =
  AuthenticatedOnboardedManageSettingsRouteImport.update({
    id: '/manage/settings',
    path: '/manage/settings',
    getParentRoute: () => AuthenticatedOnboardedRoute,
  } as any)
const AuthenticatedOnboardedFamilyKidsIndexRoute =
  AuthenticatedOnboardedFamilyKidsIndexRouteImport.update({
    id: '/family/kids/',
    path: '/family/kids/',
    getParentRoute: () => AuthenticatedOnboardedRoute,
  } as any)
const AuthenticatedOnboardedFamilyKidsProfileIdRouteRoute =
  AuthenticatedOnboardedFamilyKidsProfileIdRouteRouteImport.update({
    id: '/family/kids/$profileId',
    path: '/family/kids/$profileId',
    getParentRoute: () => AuthenticatedOnboardedRoute,
  } as any)
const AuthenticatedOnboardedFamilyKidsProfileIdIndexRoute =
  AuthenticatedOnboardedFamilyKidsProfileIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOnboardedFamilyKidsProfileIdRouteRoute,
  } as any)
const AuthenticatedOnboardedFamilyKidsProfileIdDictionaryRoute =
  AuthenticatedOnboardedFamilyKidsProfileIdDictionaryRouteImport.update({
    id: '/dictionary',
    path: '/dictionary',
    getParentRoute: () => AuthenticatedOnboardedFamilyKidsProfileIdRouteRoute,
  } as any)
const AuthenticatedOnboardedFamilyKidsProfileIdGeneralRoute =
  AuthenticatedOnboardedFamilyKidsProfileIdGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => AuthenticatedOnboardedFamilyKidsProfileIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedOnboardedIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/onboarding': typeof AuthenticatedOnboardingRouteRouteWithChildren
  '/join-household': typeof AuthenticatedJoinHouseholdRoute
  '/user-profile': typeof AuthenticatedOnboardedUserProfileRoute
  '/onboarding/create-household': typeof AuthenticatedOnboardingCreateHouseholdRoute
  '/onboarding/invite-members': typeof AuthenticatedOnboardingInviteMembersRoute
  '/onboarding/': typeof AuthenticatedOnboardingIndexRoute
  '/expenses/monthly-expenses': typeof AuthenticatedOnboardedExpensesMonthlyExpensesRoute
  '/manage/household-members': typeof AuthenticatedOnboardedManageHouseholdMembersRoute
  '/manage/settings': typeof AuthenticatedOnboardedManageSettingsRoute
  '/family/kids/$profileId': typeof AuthenticatedOnboardedFamilyKidsProfileIdRouteRouteWithChildren
  '/family/kids/': typeof AuthenticatedOnboardedFamilyKidsIndexRoute
  '/family/kids/$profileId/dictionary': typeof AuthenticatedOnboardedFamilyKidsProfileIdDictionaryRoute
  '/family/kids/$profileId/general': typeof AuthenticatedOnboardedFamilyKidsProfileIdGeneralRoute
  '/family/kids/$profileId/': typeof AuthenticatedOnboardedFamilyKidsProfileIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedOnboardedIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/join-household': typeof AuthenticatedJoinHouseholdRoute
  '/user-profile': typeof AuthenticatedOnboardedUserProfileRoute
  '/onboarding/create-household': typeof AuthenticatedOnboardingCreateHouseholdRoute
  '/onboarding/invite-members': typeof AuthenticatedOnboardingInviteMembersRoute
  '/onboarding': typeof AuthenticatedOnboardingIndexRoute
  '/expenses/monthly-expenses': typeof AuthenticatedOnboardedExpensesMonthlyExpensesRoute
  '/manage/household-members': typeof AuthenticatedOnboardedManageHouseholdMembersRoute
  '/manage/settings': typeof AuthenticatedOnboardedManageSettingsRoute
  '/family/kids': typeof AuthenticatedOnboardedFamilyKidsIndexRoute
  '/family/kids/$profileId/dictionary': typeof AuthenticatedOnboardedFamilyKidsProfileIdDictionaryRoute
  '/family/kids/$profileId/general': typeof AuthenticatedOnboardedFamilyKidsProfileIdGeneralRoute
  '/family/kids/$profileId': typeof AuthenticatedOnboardedFamilyKidsProfileIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRouteRouteWithChildren
  '/_authenticated/_onboarded': typeof AuthenticatedOnboardedRouteWithChildren
  '/_authenticated/join-household': typeof AuthenticatedJoinHouseholdRoute
  '/_authenticated/_onboarded/user-profile': typeof AuthenticatedOnboardedUserProfileRoute
  '/_authenticated/onboarding/create-household': typeof AuthenticatedOnboardingCreateHouseholdRoute
  '/_authenticated/onboarding/invite-members': typeof AuthenticatedOnboardingInviteMembersRoute
  '/_authenticated/_onboarded/': typeof AuthenticatedOnboardedIndexRoute
  '/_authenticated/onboarding/': typeof AuthenticatedOnboardingIndexRoute
  '/_authenticated/_onboarded/expenses/monthly-expenses': typeof AuthenticatedOnboardedExpensesMonthlyExpensesRoute
  '/_authenticated/_onboarded/manage/household-members': typeof AuthenticatedOnboardedManageHouseholdMembersRoute
  '/_authenticated/_onboarded/manage/settings': typeof AuthenticatedOnboardedManageSettingsRoute
  '/_authenticated/_onboarded/family/kids/$profileId': typeof AuthenticatedOnboardedFamilyKidsProfileIdRouteRouteWithChildren
  '/_authenticated/_onboarded/family/kids/': typeof AuthenticatedOnboardedFamilyKidsIndexRoute
  '/_authenticated/_onboarded/family/kids/$profileId/dictionary': typeof AuthenticatedOnboardedFamilyKidsProfileIdDictionaryRoute
  '/_authenticated/_onboarded/family/kids/$profileId/general': typeof AuthenticatedOnboardedFamilyKidsProfileIdGeneralRoute
  '/_authenticated/_onboarded/family/kids/$profileId/': typeof AuthenticatedOnboardedFamilyKidsProfileIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/verify-email'
    | '/onboarding'
    | '/join-household'
    | '/user-profile'
    | '/onboarding/create-household'
    | '/onboarding/invite-members'
    | '/onboarding/'
    | '/expenses/monthly-expenses'
    | '/manage/household-members'
    | '/manage/settings'
    | '/family/kids/$profileId'
    | '/family/kids/'
    | '/family/kids/$profileId/dictionary'
    | '/family/kids/$profileId/general'
    | '/family/kids/$profileId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/verify-email'
    | '/join-household'
    | '/user-profile'
    | '/onboarding/create-household'
    | '/onboarding/invite-members'
    | '/onboarding'
    | '/expenses/monthly-expenses'
    | '/manage/household-members'
    | '/manage/settings'
    | '/family/kids'
    | '/family/kids/$profileId/dictionary'
    | '/family/kids/$profileId/general'
    | '/family/kids/$profileId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/verify-email'
    | '/_authenticated/onboarding'
    | '/_authenticated/_onboarded'
    | '/_authenticated/join-household'
    | '/_authenticated/_onboarded/user-profile'
    | '/_authenticated/onboarding/create-household'
    | '/_authenticated/onboarding/invite-members'
    | '/_authenticated/_onboarded/'
    | '/_authenticated/onboarding/'
    | '/_authenticated/_onboarded/expenses/monthly-expenses'
    | '/_authenticated/_onboarded/manage/household-members'
    | '/_authenticated/_onboarded/manage/settings'
    | '/_authenticated/_onboarded/family/kids/$profileId'
    | '/_authenticated/_onboarded/family/kids/'
    | '/_authenticated/_onboarded/family/kids/$profileId/dictionary'
    | '/_authenticated/_onboarded/family/kids/$profileId/general'
    | '/_authenticated/_onboarded/family/kids/$profileId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_onboarded': {
      id: '/_authenticated/_onboarded'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedOnboardedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/join-household': {
      id: '/_authenticated/join-household'
      path: '/join-household'
      fullPath: '/join-household'
      preLoaderRoute: typeof AuthenticatedJoinHouseholdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_onboarded/': {
      id: '/_authenticated/_onboarded/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedOnboardedIndexRouteImport
      parentRoute: typeof AuthenticatedOnboardedRoute
    }
    '/_authenticated/_onboarded/user-profile': {
      id: '/_authenticated/_onboarded/user-profile'
      path: '/user-profile'
      fullPath: '/user-profile'
      preLoaderRoute: typeof AuthenticatedOnboardedUserProfileRouteImport
      parentRoute: typeof AuthenticatedOnboardedRoute
    }
    '/_authenticated/onboarding/': {
      id: '/_authenticated/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof AuthenticatedOnboardingIndexRouteImport
      parentRoute: typeof AuthenticatedOnboardingRouteRoute
    }
    '/_authenticated/onboarding/create-household': {
      id: '/_authenticated/onboarding/create-household'
      path: '/create-household'
      fullPath: '/onboarding/create-household'
      preLoaderRoute: typeof AuthenticatedOnboardingCreateHouseholdRouteImport
      parentRoute: typeof AuthenticatedOnboardingRouteRoute
    }
    '/_authenticated/onboarding/invite-members': {
      id: '/_authenticated/onboarding/invite-members'
      path: '/invite-members'
      fullPath: '/onboarding/invite-members'
      preLoaderRoute: typeof AuthenticatedOnboardingInviteMembersRouteImport
      parentRoute: typeof AuthenticatedOnboardingRouteRoute
    }
    '/_authenticated/_onboarded/expenses/monthly-expenses': {
      id: '/_authenticated/_onboarded/expenses/monthly-expenses'
      path: '/expenses/monthly-expenses'
      fullPath: '/expenses/monthly-expenses'
      preLoaderRoute: typeof AuthenticatedOnboardedExpensesMonthlyExpensesRouteImport
      parentRoute: typeof AuthenticatedOnboardedRoute
    }
    '/_authenticated/_onboarded/manage/household-members': {
      id: '/_authenticated/_onboarded/manage/household-members'
      path: '/manage/household-members'
      fullPath: '/manage/household-members'
      preLoaderRoute: typeof AuthenticatedOnboardedManageHouseholdMembersRouteImport
      parentRoute: typeof AuthenticatedOnboardedRoute
    }
    '/_authenticated/_onboarded/manage/settings': {
      id: '/_authenticated/_onboarded/manage/settings'
      path: '/manage/settings'
      fullPath: '/manage/settings'
      preLoaderRoute: typeof AuthenticatedOnboardedManageSettingsRouteImport
      parentRoute: typeof AuthenticatedOnboardedRoute
    }
    '/_authenticated/_onboarded/family/kids/': {
      id: '/_authenticated/_onboarded/family/kids/'
      path: '/family/kids'
      fullPath: '/family/kids/'
      preLoaderRoute: typeof AuthenticatedOnboardedFamilyKidsIndexRouteImport
      parentRoute: typeof AuthenticatedOnboardedRoute
    }
    '/_authenticated/_onboarded/family/kids/$profileId': {
      id: '/_authenticated/_onboarded/family/kids/$profileId'
      path: '/family/kids/$profileId'
      fullPath: '/family/kids/$profileId'
      preLoaderRoute: typeof AuthenticatedOnboardedFamilyKidsProfileIdRouteRouteImport
      parentRoute: typeof AuthenticatedOnboardedRoute
    }
    '/_authenticated/_onboarded/family/kids/$profileId/': {
      id: '/_authenticated/_onboarded/family/kids/$profileId/'
      path: '/'
      fullPath: '/family/kids/$profileId/'
      preLoaderRoute: typeof AuthenticatedOnboardedFamilyKidsProfileIdIndexRouteImport
      parentRoute: typeof AuthenticatedOnboardedFamilyKidsProfileIdRouteRoute
    }
    '/_authenticated/_onboarded/family/kids/$profileId/dictionary': {
      id: '/_authenticated/_onboarded/family/kids/$profileId/dictionary'
      path: '/dictionary'
      fullPath: '/family/kids/$profileId/dictionary'
      preLoaderRoute: typeof AuthenticatedOnboardedFamilyKidsProfileIdDictionaryRouteImport
      parentRoute: typeof AuthenticatedOnboardedFamilyKidsProfileIdRouteRoute
    }
    '/_authenticated/_onboarded/family/kids/$profileId/general': {
      id: '/_authenticated/_onboarded/family/kids/$profileId/general'
      path: '/general'
      fullPath: '/family/kids/$profileId/general'
      preLoaderRoute: typeof AuthenticatedOnboardedFamilyKidsProfileIdGeneralRouteImport
      parentRoute: typeof AuthenticatedOnboardedFamilyKidsProfileIdRouteRoute
    }
  }
}

interface AuthenticatedOnboardingRouteRouteChildren {
  AuthenticatedOnboardingCreateHouseholdRoute: typeof AuthenticatedOnboardingCreateHouseholdRoute
  AuthenticatedOnboardingInviteMembersRoute: typeof AuthenticatedOnboardingInviteMembersRoute
  AuthenticatedOnboardingIndexRoute: typeof AuthenticatedOnboardingIndexRoute
}

const AuthenticatedOnboardingRouteRouteChildren: AuthenticatedOnboardingRouteRouteChildren =
  {
    AuthenticatedOnboardingCreateHouseholdRoute:
      AuthenticatedOnboardingCreateHouseholdRoute,
    AuthenticatedOnboardingInviteMembersRoute:
      AuthenticatedOnboardingInviteMembersRoute,
    AuthenticatedOnboardingIndexRoute: AuthenticatedOnboardingIndexRoute,
  }

const AuthenticatedOnboardingRouteRouteWithChildren =
  AuthenticatedOnboardingRouteRoute._addFileChildren(
    AuthenticatedOnboardingRouteRouteChildren,
  )

interface AuthenticatedOnboardedFamilyKidsProfileIdRouteRouteChildren {
  AuthenticatedOnboardedFamilyKidsProfileIdDictionaryRoute: typeof AuthenticatedOnboardedFamilyKidsProfileIdDictionaryRoute
  AuthenticatedOnboardedFamilyKidsProfileIdGeneralRoute: typeof AuthenticatedOnboardedFamilyKidsProfileIdGeneralRoute
  AuthenticatedOnboardedFamilyKidsProfileIdIndexRoute: typeof AuthenticatedOnboardedFamilyKidsProfileIdIndexRoute
}

const AuthenticatedOnboardedFamilyKidsProfileIdRouteRouteChildren: AuthenticatedOnboardedFamilyKidsProfileIdRouteRouteChildren =
  {
    AuthenticatedOnboardedFamilyKidsProfileIdDictionaryRoute:
      AuthenticatedOnboardedFamilyKidsProfileIdDictionaryRoute,
    AuthenticatedOnboardedFamilyKidsProfileIdGeneralRoute:
      AuthenticatedOnboardedFamilyKidsProfileIdGeneralRoute,
    AuthenticatedOnboardedFamilyKidsProfileIdIndexRoute:
      AuthenticatedOnboardedFamilyKidsProfileIdIndexRoute,
  }

const AuthenticatedOnboardedFamilyKidsProfileIdRouteRouteWithChildren =
  AuthenticatedOnboardedFamilyKidsProfileIdRouteRoute._addFileChildren(
    AuthenticatedOnboardedFamilyKidsProfileIdRouteRouteChildren,
  )

interface AuthenticatedOnboardedRouteChildren {
  AuthenticatedOnboardedUserProfileRoute: typeof AuthenticatedOnboardedUserProfileRoute
  AuthenticatedOnboardedIndexRoute: typeof AuthenticatedOnboardedIndexRoute
  AuthenticatedOnboardedExpensesMonthlyExpensesRoute: typeof AuthenticatedOnboardedExpensesMonthlyExpensesRoute
  AuthenticatedOnboardedManageHouseholdMembersRoute: typeof AuthenticatedOnboardedManageHouseholdMembersRoute
  AuthenticatedOnboardedManageSettingsRoute: typeof AuthenticatedOnboardedManageSettingsRoute
  AuthenticatedOnboardedFamilyKidsProfileIdRouteRoute: typeof AuthenticatedOnboardedFamilyKidsProfileIdRouteRouteWithChildren
  AuthenticatedOnboardedFamilyKidsIndexRoute: typeof AuthenticatedOnboardedFamilyKidsIndexRoute
}

const AuthenticatedOnboardedRouteChildren: AuthenticatedOnboardedRouteChildren =
  {
    AuthenticatedOnboardedUserProfileRoute:
      AuthenticatedOnboardedUserProfileRoute,
    AuthenticatedOnboardedIndexRoute: AuthenticatedOnboardedIndexRoute,
    AuthenticatedOnboardedExpensesMonthlyExpensesRoute:
      AuthenticatedOnboardedExpensesMonthlyExpensesRoute,
    AuthenticatedOnboardedManageHouseholdMembersRoute:
      AuthenticatedOnboardedManageHouseholdMembersRoute,
    AuthenticatedOnboardedManageSettingsRoute:
      AuthenticatedOnboardedManageSettingsRoute,
    AuthenticatedOnboardedFamilyKidsProfileIdRouteRoute:
      AuthenticatedOnboardedFamilyKidsProfileIdRouteRouteWithChildren,
    AuthenticatedOnboardedFamilyKidsIndexRoute:
      AuthenticatedOnboardedFamilyKidsIndexRoute,
  }

const AuthenticatedOnboardedRouteWithChildren =
  AuthenticatedOnboardedRoute._addFileChildren(
    AuthenticatedOnboardedRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedOnboardingRouteRoute: typeof AuthenticatedOnboardingRouteRouteWithChildren
  AuthenticatedOnboardedRoute: typeof AuthenticatedOnboardedRouteWithChildren
  AuthenticatedJoinHouseholdRoute: typeof AuthenticatedJoinHouseholdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedOnboardingRouteRoute:
    AuthenticatedOnboardingRouteRouteWithChildren,
  AuthenticatedOnboardedRoute: AuthenticatedOnboardedRouteWithChildren,
  AuthenticatedJoinHouseholdRoute: AuthenticatedJoinHouseholdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
