/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AuthenticatedOnboardedRouteImport } from './routes/_authenticated/_onboarded'
import { Route as AuthenticatedJoinHouseholdRouteImport } from './routes/_authenticated/join-household'
import { Route as AuthenticatedOnboardingRouteRouteImport } from './routes/_authenticated/onboarding/route'
import { Route as AuthenticatedOnboardedIndexRouteImport } from './routes/_authenticated/_onboarded/index'
import { Route as AuthenticatedOnboardedGuestRouteImport } from './routes/_authenticated/_onboarded/guest'
import { Route as AuthenticatedOnboardedUserProfileRouteImport } from './routes/_authenticated/_onboarded/user-profile'
import { Route as AuthenticatedOnboardingIndexRouteImport } from './routes/_authenticated/onboarding/index'
import { Route as AuthenticatedOnboardingCreateHouseholdRouteImport } from './routes/_authenticated/onboarding/create-household'
import { Route as AuthenticatedOnboardingInviteMembersRouteImport } from './routes/_authenticated/onboarding/invite-members'
import { Route as AuthenticatedOnboardedExpensesMonthlyExpensesRouteRouteImport } from './routes/_authenticated/_onboarded/expenses/monthly-expenses/route'
import { Route as AuthenticatedOnboardedFoodIngredientsRouteRouteImport } from './routes/_authenticated/_onboarded/food/ingredients/route'
import { Route as AuthenticatedOnboardedFoodShoppingListsRouteRouteImport } from './routes/_authenticated/_onboarded/food/shopping-lists/route'
import { Route as AuthenticatedOnboardedManageActivityRouteImport } from './routes/_authenticated/_onboarded/manage/activity'
import { Route as AuthenticatedOnboardedManageHouseholdMembersRouteImport } from './routes/_authenticated/_onboarded/manage/household-members'
import { Route as AuthenticatedOnboardedManageSettingsRouteImport } from './routes/_authenticated/_onboarded/manage/settings'
import { Route as AuthenticatedOnboardedExpensesMonthlyExpensesIndexRouteImport } from './routes/_authenticated/_onboarded/expenses/monthly-expenses/index'
import { Route as AuthenticatedOnboardedExpensesMonthlyExpensesCategoriesRouteImport } from './routes/_authenticated/_onboarded/expenses/monthly-expenses/categories'
import { Route as AuthenticatedOnboardedFamilyContactsIndexRouteImport } from './routes/_authenticated/_onboarded/family/contacts/index'
import { Route as AuthenticatedOnboardedFamilyContactsContactIdRouteImport } from './routes/_authenticated/_onboarded/family/contacts/$contactId'
import { Route as AuthenticatedOnboardedFamilyKidsIndexRouteImport } from './routes/_authenticated/_onboarded/family/kids/index'
import { Route as AuthenticatedOnboardedFamilyKidsProfileIdRouteRouteImport } from './routes/_authenticated/_onboarded/family/kids/$profileId/route'
import { Route as AuthenticatedOnboardedFamilyPetsIndexRouteImport } from './routes/_authenticated/_onboarded/family/pets/index'
import { Route as AuthenticatedOnboardedFamilyPetsProfileIdRouteRouteImport } from './routes/_authenticated/_onboarded/family/pets/$profileId/route'
import { Route as AuthenticatedOnboardedFoodIngredientsIndexRouteImport } from './routes/_authenticated/_onboarded/food/ingredients/index'
import { Route as AuthenticatedOnboardedFoodIngredientsStoresRouteImport } from './routes/_authenticated/_onboarded/food/ingredients/stores'
import { Route as AuthenticatedOnboardedFoodMealPlanIndexRouteImport } from './routes/_authenticated/_onboarded/food/meal-plan/index'
import { Route as AuthenticatedOnboardedFoodRecipesIndexRouteImport } from './routes/_authenticated/_onboarded/food/recipes/index'
import { Route as AuthenticatedOnboardedFoodRecipesRecipeIdRouteRouteImport } from './routes/_authenticated/_onboarded/food/recipes/$recipeId/route'
import { Route as AuthenticatedOnboardedFoodRecipesNewRouteImport } from './routes/_authenticated/_onboarded/food/recipes/new'
import { Route as AuthenticatedOnboardedFoodShoppingListsIndexRouteImport } from './routes/_authenticated/_onboarded/food/shopping-lists/index'
import { Route as AuthenticatedOnboardedFoodShoppingListsListIdRouteImport } from './routes/_authenticated/_onboarded/food/shopping-lists/$listId'
import { Route as AuthenticatedOnboardedFoodShoppingListsImportRouteImport } from './routes/_authenticated/_onboarded/food/shopping-lists/import'
import { Route as AuthenticatedOnboardedStorageItemsIndexRouteImport } from './routes/_authenticated/_onboarded/storage/items/index'
import { Route as AuthenticatedOnboardedStorageLocationsIndexRouteImport } from './routes/_authenticated/_onboarded/storage/locations/index'
import { Route as AuthenticatedOnboardedStorageLocationsLocationIdRouteImport } from './routes/_authenticated/_onboarded/storage/locations/$locationId'
import { Route as AuthenticatedOnboardedFamilyKidsProfileIdIndexRouteImport } from './routes/_authenticated/_onboarded/family/kids/$profileId/index'
import { Route as AuthenticatedOnboardedFamilyKidsProfileIdDictionaryRouteImport } from './routes/_authenticated/_onboarded/family/kids/$profileId/dictionary'
import { Route as AuthenticatedOnboardedFamilyKidsProfileIdGeneralRouteImport } from './routes/_authenticated/_onboarded/family/kids/$profileId/general'
import { Route as AuthenticatedOnboardedFamilyPetsProfileIdIndexRouteImport } from './routes/_authenticated/_onboarded/family/pets/$profileId/index'
import { Route as AuthenticatedOnboardedFamilyPetsProfileIdGeneralRouteImport } from './routes/_authenticated/_onboarded/family/pets/$profileId/general'
import { Route as AuthenticatedOnboardedFoodRecipesRecipeIdIndexRouteImport } from './routes/_authenticated/_onboarded/food/recipes/$recipeId/index'
import { Route as AuthenticatedOnboardedFoodRecipesRecipeIdEditRouteImport } from './routes/_authenticated/_onboarded/food/recipes/$recipeId/edit'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardedRoute = AuthenticatedOnboardedRouteImport.update({
  id: '/_onboarded',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJoinHouseholdRoute =
  AuthenticatedJoinHouseholdRouteImport.update({
    id: '/join-household',
    path: '/join-household',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardingRouteRoute =
  AuthenticatedOnboardingRouteRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardedIndexRoute =
  AuthenticatedOnboardedIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOnboardedRoute,
  } as any)
const AuthenticatedOnboardedGuestRoute =
  AuthenticatedOnboardedGuestRouteImport.update({
    id: '/guest',
    path: '/guest',
    getParentRoute: () => AuthenticatedOnboardedRoute,
  } as any)
const AuthenticatedOnboardedUserProfileRoute =
  AuthenticatedOnboardedUserProfileRouteImport.update({
    id: '/user-profile',
    path: '/user-profile',
    getParentRoute: () => AuthenticatedOnboardedRoute,
  } as any)
const AuthenticatedOnboardingIndexRoute =
  AuthenticatedOnboardingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOnboardingRouteRoute,
  } as any)
const AuthenticatedOnboardingCreateHouseholdRoute =
  AuthenticatedOnboardingCreateHouseholdRouteImport.update({
    id: '/create-household',
    path: '/create-household',
    getParentRoute: () => AuthenticatedOnboardingRouteRoute,
  } as any)
const AuthenticatedOnboardingInviteMembersRoute =
  AuthenticatedOnboardingInviteMembersRouteImport.update({
    id: '/invite-members',
    path: '/invite-members',
    getParentRoute: () => AuthenticatedOnboardingRouteRoute,
  } as any)
const AuthenticatedOnboardedExpensesMonthlyExpensesRouteRoute =
  AuthenticatedOnboardedExpensesMonthlyExpensesRouteRouteImport.update({
    id: '/expenses/monthly-expenses',
    path: '/expenses/monthly-expenses',
    getParentRoute: () => AuthenticatedOnboardedRoute,
  } as any)
const AuthenticatedOnboardedFoodIngredientsRouteRoute =
  AuthenticatedOnboardedFoodIngredientsRouteRouteImport.update({
    id: '/food/ingredients',
    path: '/food/ingredients',
    getParentRoute: () => AuthenticatedOnboardedRoute,
  } as any)
const AuthenticatedOnboardedFoodShoppingListsRouteRoute =
  AuthenticatedOnboardedFoodShoppingListsRouteRouteImport.update({
    id: '/food/shopping-lists',
    path: '/food/shopping-lists',
    getParentRoute: () => AuthenticatedOnboardedRoute,
  } as any)
const AuthenticatedOnboardedManageActivityRoute =
  AuthenticatedOnboardedManageActivityRouteImport.update({
    id: '/manage/activity',
    path: '/manage/activity',
    getParentRoute: () => AuthenticatedOnboardedRoute,
  } as any)
const AuthenticatedOnboardedManageHouseholdMembersRoute =
  AuthenticatedOnboardedManageHouseholdMembersRouteImport.update({
    id: '/manage/household-members',
    path: '/manage/household-members',
    getParentRoute: () => AuthenticatedOnboardedRoute,
  } as any)
const AuthenticatedOnboardedManageSettingsRoute =
  AuthenticatedOnboardedManageSettingsRouteImport.update({
    id: '/manage/settings',
    path: '/manage/settings',
    getParentRoute: () => AuthenticatedOnboardedRoute,
  } as any)
const AuthenticatedOnboardedExpensesMonthlyExpensesIndexRoute =
  AuthenticatedOnboardedExpensesMonthlyExpensesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      AuthenticatedOnboardedExpensesMonthlyExpensesRouteRoute,
  } as any)
const AuthenticatedOnboardedExpensesMonthlyExpensesCategoriesRoute =
  AuthenticatedOnboardedExpensesMonthlyExpensesCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () =>
      AuthenticatedOnboardedExpensesMonthlyExpensesRouteRoute,
  } as any)
const AuthenticatedOnboardedFamilyContactsIndexRoute =
  AuthenticatedOnboardedFamilyContactsIndexRouteImport.update({
    id: '/family/contacts/',
    path: '/family/contacts/',
    getParentRoute: () => AuthenticatedOnboardedRoute,
  } as any)
const AuthenticatedOnboardedFamilyContactsContactIdRoute =
  AuthenticatedOnboardedFamilyContactsContactIdRouteImport.update({
    id: '/family/contacts/$contactId',
    path: '/family/contacts/$contactId',
    getParentRoute: () => AuthenticatedOnboardedRoute,
  } as any)
const AuthenticatedOnboardedFamilyKidsIndexRoute =
  AuthenticatedOnboardedFamilyKidsIndexRouteImport.update({
    id: '/family/kids/',
    path: '/family/kids/',
    getParentRoute: () => AuthenticatedOnboardedRoute,
  } as any)
const AuthenticatedOnboardedFamilyKidsProfileIdRouteRoute =
  AuthenticatedOnboardedFamilyKidsProfileIdRouteRouteImport.update({
    id: '/family/kids/$profileId',
    path: '/family/kids/$profileId',
    getParentRoute: () => AuthenticatedOnboardedRoute,
  } as any)
const AuthenticatedOnboardedFamilyPetsIndexRoute =
  AuthenticatedOnboardedFamilyPetsIndexRouteImport.update({
    id: '/family/pets/',
    path: '/family/pets/',
    getParentRoute: () => AuthenticatedOnboardedRoute,
  } as any)
const AuthenticatedOnboardedFamilyPetsProfileIdRouteRoute =
  AuthenticatedOnboardedFamilyPetsProfileIdRouteRouteImport.update({
    id: '/family/pets/$profileId',
    path: '/family/pets/$profileId',
    getParentRoute: () => AuthenticatedOnboardedRoute,
  } as any)
const AuthenticatedOnboardedFoodIngredientsIndexRoute =
  AuthenticatedOnboardedFoodIngredientsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOnboardedFoodIngredientsRouteRoute,
  } as any)
const AuthenticatedOnboardedFoodIngredientsStoresRoute =
  AuthenticatedOnboardedFoodIngredientsStoresRouteImport.update({
    id: '/stores',
    path: '/stores',
    getParentRoute: () => AuthenticatedOnboardedFoodIngredientsRouteRoute,
  } as any)
const AuthenticatedOnboardedFoodMealPlanIndexRoute =
  AuthenticatedOnboardedFoodMealPlanIndexRouteImport.update({
    id: '/food/meal-plan/',
    path: '/food/meal-plan/',
    getParentRoute: () => AuthenticatedOnboardedRoute,
  } as any)
const AuthenticatedOnboardedFoodRecipesIndexRoute =
  AuthenticatedOnboardedFoodRecipesIndexRouteImport.update({
    id: '/food/recipes/',
    path: '/food/recipes/',
    getParentRoute: () => AuthenticatedOnboardedRoute,
  } as any)
const AuthenticatedOnboardedFoodRecipesRecipeIdRouteRoute =
  AuthenticatedOnboardedFoodRecipesRecipeIdRouteRouteImport.update({
    id: '/food/recipes/$recipeId',
    path: '/food/recipes/$recipeId',
    getParentRoute: () => AuthenticatedOnboardedRoute,
  } as any)
const AuthenticatedOnboardedFoodRecipesNewRoute =
  AuthenticatedOnboardedFoodRecipesNewRouteImport.update({
    id: '/food/recipes/new',
    path: '/food/recipes/new',
    getParentRoute: () => AuthenticatedOnboardedRoute,
  } as any)
const AuthenticatedOnboardedFoodShoppingListsIndexRoute =
  AuthenticatedOnboardedFoodShoppingListsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOnboardedFoodShoppingListsRouteRoute,
  } as any)
const AuthenticatedOnboardedFoodShoppingListsListIdRoute =
  AuthenticatedOnboardedFoodShoppingListsListIdRouteImport.update({
    id: '/$listId',
    path: '/$listId',
    getParentRoute: () => AuthenticatedOnboardedFoodShoppingListsRouteRoute,
  } as any)
const AuthenticatedOnboardedFoodShoppingListsImportRoute =
  AuthenticatedOnboardedFoodShoppingListsImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedOnboardedFoodShoppingListsRouteRoute,
  } as any)
const AuthenticatedOnboardedStorageItemsIndexRoute =
  AuthenticatedOnboardedStorageItemsIndexRouteImport.update({
    id: '/storage/items/',
    path: '/storage/items/',
    getParentRoute: () => AuthenticatedOnboardedRoute,
  } as any)
const AuthenticatedOnboardedStorageLocationsIndexRoute =
  AuthenticatedOnboardedStorageLocationsIndexRouteImport.update({
    id: '/storage/locations/',
    path: '/storage/locations/',
    getParentRoute: () => AuthenticatedOnboardedRoute,
  } as any)
const AuthenticatedOnboardedStorageLocationsLocationIdRoute =
  AuthenticatedOnboardedStorageLocationsLocationIdRouteImport.update({
    id: '/storage/locations/$locationId',
    path: '/storage/locations/$locationId',
    getParentRoute: () => AuthenticatedOnboardedRoute,
  } as any)
const AuthenticatedOnboardedFamilyKidsProfileIdIndexRoute =
  AuthenticatedOnboardedFamilyKidsProfileIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOnboardedFamilyKidsProfileIdRouteRoute,
  } as any)
const AuthenticatedOnboardedFamilyKidsProfileIdDictionaryRoute =
  AuthenticatedOnboardedFamilyKidsProfileIdDictionaryRouteImport.update({
    id: '/dictionary',
    path: '/dictionary',
    getParentRoute: () => AuthenticatedOnboardedFamilyKidsProfileIdRouteRoute,
  } as any)
const AuthenticatedOnboardedFamilyKidsProfileIdGeneralRoute =
  AuthenticatedOnboardedFamilyKidsProfileIdGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => AuthenticatedOnboardedFamilyKidsProfileIdRouteRoute,
  } as any)
const AuthenticatedOnboardedFamilyPetsProfileIdIndexRoute =
  AuthenticatedOnboardedFamilyPetsProfileIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOnboardedFamilyPetsProfileIdRouteRoute,
  } as any)
const AuthenticatedOnboardedFamilyPetsProfileIdGeneralRoute =
  AuthenticatedOnboardedFamilyPetsProfileIdGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => AuthenticatedOnboardedFamilyPetsProfileIdRouteRoute,
  } as any)
const AuthenticatedOnboardedFoodRecipesRecipeIdIndexRoute =
  AuthenticatedOnboardedFoodRecipesRecipeIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOnboardedFoodRecipesRecipeIdRouteRoute,
  } as any)
const AuthenticatedOnboardedFoodRecipesRecipeIdEditRoute =
  AuthenticatedOnboardedFoodRecipesRecipeIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedOnboardedFoodRecipesRecipeIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedOnboardedIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/onboarding': typeof AuthenticatedOnboardingRouteRouteWithChildren
  '/join-household': typeof AuthenticatedJoinHouseholdRoute
  '/guest': typeof AuthenticatedOnboardedGuestRoute
  '/user-profile': typeof AuthenticatedOnboardedUserProfileRoute
  '/onboarding/create-household': typeof AuthenticatedOnboardingCreateHouseholdRoute
  '/onboarding/invite-members': typeof AuthenticatedOnboardingInviteMembersRoute
  '/onboarding/': typeof AuthenticatedOnboardingIndexRoute
  '/expenses/monthly-expenses': typeof AuthenticatedOnboardedExpensesMonthlyExpensesRouteRouteWithChildren
  '/food/ingredients': typeof AuthenticatedOnboardedFoodIngredientsRouteRouteWithChildren
  '/food/shopping-lists': typeof AuthenticatedOnboardedFoodShoppingListsRouteRouteWithChildren
  '/manage/activity': typeof AuthenticatedOnboardedManageActivityRoute
  '/manage/household-members': typeof AuthenticatedOnboardedManageHouseholdMembersRoute
  '/manage/settings': typeof AuthenticatedOnboardedManageSettingsRoute
  '/family/kids/$profileId': typeof AuthenticatedOnboardedFamilyKidsProfileIdRouteRouteWithChildren
  '/family/pets/$profileId': typeof AuthenticatedOnboardedFamilyPetsProfileIdRouteRouteWithChildren
  '/food/recipes/$recipeId': typeof AuthenticatedOnboardedFoodRecipesRecipeIdRouteRouteWithChildren
  '/expenses/monthly-expenses/categories': typeof AuthenticatedOnboardedExpensesMonthlyExpensesCategoriesRoute
  '/family/contacts/$contactId': typeof AuthenticatedOnboardedFamilyContactsContactIdRoute
  '/food/ingredients/stores': typeof AuthenticatedOnboardedFoodIngredientsStoresRoute
  '/food/recipes/new': typeof AuthenticatedOnboardedFoodRecipesNewRoute
  '/food/shopping-lists/$listId': typeof AuthenticatedOnboardedFoodShoppingListsListIdRoute
  '/food/shopping-lists/import': typeof AuthenticatedOnboardedFoodShoppingListsImportRoute
  '/storage/locations/$locationId': typeof AuthenticatedOnboardedStorageLocationsLocationIdRoute
  '/expenses/monthly-expenses/': typeof AuthenticatedOnboardedExpensesMonthlyExpensesIndexRoute
  '/family/contacts/': typeof AuthenticatedOnboardedFamilyContactsIndexRoute
  '/family/kids/': typeof AuthenticatedOnboardedFamilyKidsIndexRoute
  '/family/pets/': typeof AuthenticatedOnboardedFamilyPetsIndexRoute
  '/food/ingredients/': typeof AuthenticatedOnboardedFoodIngredientsIndexRoute
  '/food/meal-plan/': typeof AuthenticatedOnboardedFoodMealPlanIndexRoute
  '/food/recipes/': typeof AuthenticatedOnboardedFoodRecipesIndexRoute
  '/food/shopping-lists/': typeof AuthenticatedOnboardedFoodShoppingListsIndexRoute
  '/storage/items/': typeof AuthenticatedOnboardedStorageItemsIndexRoute
  '/storage/locations/': typeof AuthenticatedOnboardedStorageLocationsIndexRoute
  '/family/kids/$profileId/dictionary': typeof AuthenticatedOnboardedFamilyKidsProfileIdDictionaryRoute
  '/family/kids/$profileId/general': typeof AuthenticatedOnboardedFamilyKidsProfileIdGeneralRoute
  '/family/pets/$profileId/general': typeof AuthenticatedOnboardedFamilyPetsProfileIdGeneralRoute
  '/food/recipes/$recipeId/edit': typeof AuthenticatedOnboardedFoodRecipesRecipeIdEditRoute
  '/family/kids/$profileId/': typeof AuthenticatedOnboardedFamilyKidsProfileIdIndexRoute
  '/family/pets/$profileId/': typeof AuthenticatedOnboardedFamilyPetsProfileIdIndexRoute
  '/food/recipes/$recipeId/': typeof AuthenticatedOnboardedFoodRecipesRecipeIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedOnboardedIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/join-household': typeof AuthenticatedJoinHouseholdRoute
  '/guest': typeof AuthenticatedOnboardedGuestRoute
  '/user-profile': typeof AuthenticatedOnboardedUserProfileRoute
  '/onboarding/create-household': typeof AuthenticatedOnboardingCreateHouseholdRoute
  '/onboarding/invite-members': typeof AuthenticatedOnboardingInviteMembersRoute
  '/onboarding': typeof AuthenticatedOnboardingIndexRoute
  '/manage/activity': typeof AuthenticatedOnboardedManageActivityRoute
  '/manage/household-members': typeof AuthenticatedOnboardedManageHouseholdMembersRoute
  '/manage/settings': typeof AuthenticatedOnboardedManageSettingsRoute
  '/expenses/monthly-expenses/categories': typeof AuthenticatedOnboardedExpensesMonthlyExpensesCategoriesRoute
  '/family/contacts/$contactId': typeof AuthenticatedOnboardedFamilyContactsContactIdRoute
  '/food/ingredients/stores': typeof AuthenticatedOnboardedFoodIngredientsStoresRoute
  '/food/recipes/new': typeof AuthenticatedOnboardedFoodRecipesNewRoute
  '/food/shopping-lists/$listId': typeof AuthenticatedOnboardedFoodShoppingListsListIdRoute
  '/food/shopping-lists/import': typeof AuthenticatedOnboardedFoodShoppingListsImportRoute
  '/storage/locations/$locationId': typeof AuthenticatedOnboardedStorageLocationsLocationIdRoute
  '/expenses/monthly-expenses': typeof AuthenticatedOnboardedExpensesMonthlyExpensesIndexRoute
  '/family/contacts': typeof AuthenticatedOnboardedFamilyContactsIndexRoute
  '/family/kids': typeof AuthenticatedOnboardedFamilyKidsIndexRoute
  '/family/pets': typeof AuthenticatedOnboardedFamilyPetsIndexRoute
  '/food/ingredients': typeof AuthenticatedOnboardedFoodIngredientsIndexRoute
  '/food/meal-plan': typeof AuthenticatedOnboardedFoodMealPlanIndexRoute
  '/food/recipes': typeof AuthenticatedOnboardedFoodRecipesIndexRoute
  '/food/shopping-lists': typeof AuthenticatedOnboardedFoodShoppingListsIndexRoute
  '/storage/items': typeof AuthenticatedOnboardedStorageItemsIndexRoute
  '/storage/locations': typeof AuthenticatedOnboardedStorageLocationsIndexRoute
  '/family/kids/$profileId/dictionary': typeof AuthenticatedOnboardedFamilyKidsProfileIdDictionaryRoute
  '/family/kids/$profileId/general': typeof AuthenticatedOnboardedFamilyKidsProfileIdGeneralRoute
  '/family/pets/$profileId/general': typeof AuthenticatedOnboardedFamilyPetsProfileIdGeneralRoute
  '/food/recipes/$recipeId/edit': typeof AuthenticatedOnboardedFoodRecipesRecipeIdEditRoute
  '/family/kids/$profileId': typeof AuthenticatedOnboardedFamilyKidsProfileIdIndexRoute
  '/family/pets/$profileId': typeof AuthenticatedOnboardedFamilyPetsProfileIdIndexRoute
  '/food/recipes/$recipeId': typeof AuthenticatedOnboardedFoodRecipesRecipeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRouteRouteWithChildren
  '/_authenticated/_onboarded': typeof AuthenticatedOnboardedRouteWithChildren
  '/_authenticated/join-household': typeof AuthenticatedJoinHouseholdRoute
  '/_authenticated/_onboarded/guest': typeof AuthenticatedOnboardedGuestRoute
  '/_authenticated/_onboarded/user-profile': typeof AuthenticatedOnboardedUserProfileRoute
  '/_authenticated/onboarding/create-household': typeof AuthenticatedOnboardingCreateHouseholdRoute
  '/_authenticated/onboarding/invite-members': typeof AuthenticatedOnboardingInviteMembersRoute
  '/_authenticated/_onboarded/': typeof AuthenticatedOnboardedIndexRoute
  '/_authenticated/onboarding/': typeof AuthenticatedOnboardingIndexRoute
  '/_authenticated/_onboarded/expenses/monthly-expenses': typeof AuthenticatedOnboardedExpensesMonthlyExpensesRouteRouteWithChildren
  '/_authenticated/_onboarded/food/ingredients': typeof AuthenticatedOnboardedFoodIngredientsRouteRouteWithChildren
  '/_authenticated/_onboarded/food/shopping-lists': typeof AuthenticatedOnboardedFoodShoppingListsRouteRouteWithChildren
  '/_authenticated/_onboarded/manage/activity': typeof AuthenticatedOnboardedManageActivityRoute
  '/_authenticated/_onboarded/manage/household-members': typeof AuthenticatedOnboardedManageHouseholdMembersRoute
  '/_authenticated/_onboarded/manage/settings': typeof AuthenticatedOnboardedManageSettingsRoute
  '/_authenticated/_onboarded/family/kids/$profileId': typeof AuthenticatedOnboardedFamilyKidsProfileIdRouteRouteWithChildren
  '/_authenticated/_onboarded/family/pets/$profileId': typeof AuthenticatedOnboardedFamilyPetsProfileIdRouteRouteWithChildren
  '/_authenticated/_onboarded/food/recipes/$recipeId': typeof AuthenticatedOnboardedFoodRecipesRecipeIdRouteRouteWithChildren
  '/_authenticated/_onboarded/expenses/monthly-expenses/categories': typeof AuthenticatedOnboardedExpensesMonthlyExpensesCategoriesRoute
  '/_authenticated/_onboarded/family/contacts/$contactId': typeof AuthenticatedOnboardedFamilyContactsContactIdRoute
  '/_authenticated/_onboarded/food/ingredients/stores': typeof AuthenticatedOnboardedFoodIngredientsStoresRoute
  '/_authenticated/_onboarded/food/recipes/new': typeof AuthenticatedOnboardedFoodRecipesNewRoute
  '/_authenticated/_onboarded/food/shopping-lists/$listId': typeof AuthenticatedOnboardedFoodShoppingListsListIdRoute
  '/_authenticated/_onboarded/food/shopping-lists/import': typeof AuthenticatedOnboardedFoodShoppingListsImportRoute
  '/_authenticated/_onboarded/storage/locations/$locationId': typeof AuthenticatedOnboardedStorageLocationsLocationIdRoute
  '/_authenticated/_onboarded/expenses/monthly-expenses/': typeof AuthenticatedOnboardedExpensesMonthlyExpensesIndexRoute
  '/_authenticated/_onboarded/family/contacts/': typeof AuthenticatedOnboardedFamilyContactsIndexRoute
  '/_authenticated/_onboarded/family/kids/': typeof AuthenticatedOnboardedFamilyKidsIndexRoute
  '/_authenticated/_onboarded/family/pets/': typeof AuthenticatedOnboardedFamilyPetsIndexRoute
  '/_authenticated/_onboarded/food/ingredients/': typeof AuthenticatedOnboardedFoodIngredientsIndexRoute
  '/_authenticated/_onboarded/food/meal-plan/': typeof AuthenticatedOnboardedFoodMealPlanIndexRoute
  '/_authenticated/_onboarded/food/recipes/': typeof AuthenticatedOnboardedFoodRecipesIndexRoute
  '/_authenticated/_onboarded/food/shopping-lists/': typeof AuthenticatedOnboardedFoodShoppingListsIndexRoute
  '/_authenticated/_onboarded/storage/items/': typeof AuthenticatedOnboardedStorageItemsIndexRoute
  '/_authenticated/_onboarded/storage/locations/': typeof AuthenticatedOnboardedStorageLocationsIndexRoute
  '/_authenticated/_onboarded/family/kids/$profileId/dictionary': typeof AuthenticatedOnboardedFamilyKidsProfileIdDictionaryRoute
  '/_authenticated/_onboarded/family/kids/$profileId/general': typeof AuthenticatedOnboardedFamilyKidsProfileIdGeneralRoute
  '/_authenticated/_onboarded/family/pets/$profileId/general': typeof AuthenticatedOnboardedFamilyPetsProfileIdGeneralRoute
  '/_authenticated/_onboarded/food/recipes/$recipeId/edit': typeof AuthenticatedOnboardedFoodRecipesRecipeIdEditRoute
  '/_authenticated/_onboarded/family/kids/$profileId/': typeof AuthenticatedOnboardedFamilyKidsProfileIdIndexRoute
  '/_authenticated/_onboarded/family/pets/$profileId/': typeof AuthenticatedOnboardedFamilyPetsProfileIdIndexRoute
  '/_authenticated/_onboarded/food/recipes/$recipeId/': typeof AuthenticatedOnboardedFoodRecipesRecipeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/verify-email'
    | '/onboarding'
    | '/join-household'
    | '/guest'
    | '/user-profile'
    | '/onboarding/create-household'
    | '/onboarding/invite-members'
    | '/onboarding/'
    | '/expenses/monthly-expenses'
    | '/food/ingredients'
    | '/food/shopping-lists'
    | '/manage/activity'
    | '/manage/household-members'
    | '/manage/settings'
    | '/family/kids/$profileId'
    | '/family/pets/$profileId'
    | '/food/recipes/$recipeId'
    | '/expenses/monthly-expenses/categories'
    | '/family/contacts/$contactId'
    | '/food/ingredients/stores'
    | '/food/recipes/new'
    | '/food/shopping-lists/$listId'
    | '/food/shopping-lists/import'
    | '/storage/locations/$locationId'
    | '/expenses/monthly-expenses/'
    | '/family/contacts/'
    | '/family/kids/'
    | '/family/pets/'
    | '/food/ingredients/'
    | '/food/meal-plan/'
    | '/food/recipes/'
    | '/food/shopping-lists/'
    | '/storage/items/'
    | '/storage/locations/'
    | '/family/kids/$profileId/dictionary'
    | '/family/kids/$profileId/general'
    | '/family/pets/$profileId/general'
    | '/food/recipes/$recipeId/edit'
    | '/family/kids/$profileId/'
    | '/family/pets/$profileId/'
    | '/food/recipes/$recipeId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/verify-email'
    | '/join-household'
    | '/guest'
    | '/user-profile'
    | '/onboarding/create-household'
    | '/onboarding/invite-members'
    | '/onboarding'
    | '/manage/activity'
    | '/manage/household-members'
    | '/manage/settings'
    | '/expenses/monthly-expenses/categories'
    | '/family/contacts/$contactId'
    | '/food/ingredients/stores'
    | '/food/recipes/new'
    | '/food/shopping-lists/$listId'
    | '/food/shopping-lists/import'
    | '/storage/locations/$locationId'
    | '/expenses/monthly-expenses'
    | '/family/contacts'
    | '/family/kids'
    | '/family/pets'
    | '/food/ingredients'
    | '/food/meal-plan'
    | '/food/recipes'
    | '/food/shopping-lists'
    | '/storage/items'
    | '/storage/locations'
    | '/family/kids/$profileId/dictionary'
    | '/family/kids/$profileId/general'
    | '/family/pets/$profileId/general'
    | '/food/recipes/$recipeId/edit'
    | '/family/kids/$profileId'
    | '/family/pets/$profileId'
    | '/food/recipes/$recipeId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/verify-email'
    | '/_authenticated/onboarding'
    | '/_authenticated/_onboarded'
    | '/_authenticated/join-household'
    | '/_authenticated/_onboarded/guest'
    | '/_authenticated/_onboarded/user-profile'
    | '/_authenticated/onboarding/create-household'
    | '/_authenticated/onboarding/invite-members'
    | '/_authenticated/_onboarded/'
    | '/_authenticated/onboarding/'
    | '/_authenticated/_onboarded/expenses/monthly-expenses'
    | '/_authenticated/_onboarded/food/ingredients'
    | '/_authenticated/_onboarded/food/shopping-lists'
    | '/_authenticated/_onboarded/manage/activity'
    | '/_authenticated/_onboarded/manage/household-members'
    | '/_authenticated/_onboarded/manage/settings'
    | '/_authenticated/_onboarded/family/kids/$profileId'
    | '/_authenticated/_onboarded/family/pets/$profileId'
    | '/_authenticated/_onboarded/food/recipes/$recipeId'
    | '/_authenticated/_onboarded/expenses/monthly-expenses/categories'
    | '/_authenticated/_onboarded/family/contacts/$contactId'
    | '/_authenticated/_onboarded/food/ingredients/stores'
    | '/_authenticated/_onboarded/food/recipes/new'
    | '/_authenticated/_onboarded/food/shopping-lists/$listId'
    | '/_authenticated/_onboarded/food/shopping-lists/import'
    | '/_authenticated/_onboarded/storage/locations/$locationId'
    | '/_authenticated/_onboarded/expenses/monthly-expenses/'
    | '/_authenticated/_onboarded/family/contacts/'
    | '/_authenticated/_onboarded/family/kids/'
    | '/_authenticated/_onboarded/family/pets/'
    | '/_authenticated/_onboarded/food/ingredients/'
    | '/_authenticated/_onboarded/food/meal-plan/'
    | '/_authenticated/_onboarded/food/recipes/'
    | '/_authenticated/_onboarded/food/shopping-lists/'
    | '/_authenticated/_onboarded/storage/items/'
    | '/_authenticated/_onboarded/storage/locations/'
    | '/_authenticated/_onboarded/family/kids/$profileId/dictionary'
    | '/_authenticated/_onboarded/family/kids/$profileId/general'
    | '/_authenticated/_onboarded/family/pets/$profileId/general'
    | '/_authenticated/_onboarded/food/recipes/$recipeId/edit'
    | '/_authenticated/_onboarded/family/kids/$profileId/'
    | '/_authenticated/_onboarded/family/pets/$profileId/'
    | '/_authenticated/_onboarded/food/recipes/$recipeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_onboarded': {
      id: '/_authenticated/_onboarded'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedOnboardedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/join-household': {
      id: '/_authenticated/join-household'
      path: '/join-household'
      fullPath: '/join-household'
      preLoaderRoute: typeof AuthenticatedJoinHouseholdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_onboarded/': {
      id: '/_authenticated/_onboarded/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedOnboardedIndexRouteImport
      parentRoute: typeof AuthenticatedOnboardedRoute
    }
    '/_authenticated/_onboarded/guest': {
      id: '/_authenticated/_onboarded/guest'
      path: '/guest'
      fullPath: '/guest'
      preLoaderRoute: typeof AuthenticatedOnboardedGuestRouteImport
      parentRoute: typeof AuthenticatedOnboardedRoute
    }
    '/_authenticated/_onboarded/user-profile': {
      id: '/_authenticated/_onboarded/user-profile'
      path: '/user-profile'
      fullPath: '/user-profile'
      preLoaderRoute: typeof AuthenticatedOnboardedUserProfileRouteImport
      parentRoute: typeof AuthenticatedOnboardedRoute
    }
    '/_authenticated/onboarding/': {
      id: '/_authenticated/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof AuthenticatedOnboardingIndexRouteImport
      parentRoute: typeof AuthenticatedOnboardingRouteRoute
    }
    '/_authenticated/onboarding/create-household': {
      id: '/_authenticated/onboarding/create-household'
      path: '/create-household'
      fullPath: '/onboarding/create-household'
      preLoaderRoute: typeof AuthenticatedOnboardingCreateHouseholdRouteImport
      parentRoute: typeof AuthenticatedOnboardingRouteRoute
    }
    '/_authenticated/onboarding/invite-members': {
      id: '/_authenticated/onboarding/invite-members'
      path: '/invite-members'
      fullPath: '/onboarding/invite-members'
      preLoaderRoute: typeof AuthenticatedOnboardingInviteMembersRouteImport
      parentRoute: typeof AuthenticatedOnboardingRouteRoute
    }
    '/_authenticated/_onboarded/expenses/monthly-expenses': {
      id: '/_authenticated/_onboarded/expenses/monthly-expenses'
      path: '/expenses/monthly-expenses'
      fullPath: '/expenses/monthly-expenses'
      preLoaderRoute: typeof AuthenticatedOnboardedExpensesMonthlyExpensesRouteRouteImport
      parentRoute: typeof AuthenticatedOnboardedRoute
    }
    '/_authenticated/_onboarded/food/ingredients': {
      id: '/_authenticated/_onboarded/food/ingredients'
      path: '/food/ingredients'
      fullPath: '/food/ingredients'
      preLoaderRoute: typeof AuthenticatedOnboardedFoodIngredientsRouteRouteImport
      parentRoute: typeof AuthenticatedOnboardedRoute
    }
    '/_authenticated/_onboarded/food/shopping-lists': {
      id: '/_authenticated/_onboarded/food/shopping-lists'
      path: '/food/shopping-lists'
      fullPath: '/food/shopping-lists'
      preLoaderRoute: typeof AuthenticatedOnboardedFoodShoppingListsRouteRouteImport
      parentRoute: typeof AuthenticatedOnboardedRoute
    }
    '/_authenticated/_onboarded/manage/activity': {
      id: '/_authenticated/_onboarded/manage/activity'
      path: '/manage/activity'
      fullPath: '/manage/activity'
      preLoaderRoute: typeof AuthenticatedOnboardedManageActivityRouteImport
      parentRoute: typeof AuthenticatedOnboardedRoute
    }
    '/_authenticated/_onboarded/manage/household-members': {
      id: '/_authenticated/_onboarded/manage/household-members'
      path: '/manage/household-members'
      fullPath: '/manage/household-members'
      preLoaderRoute: typeof AuthenticatedOnboardedManageHouseholdMembersRouteImport
      parentRoute: typeof AuthenticatedOnboardedRoute
    }
    '/_authenticated/_onboarded/manage/settings': {
      id: '/_authenticated/_onboarded/manage/settings'
      path: '/manage/settings'
      fullPath: '/manage/settings'
      preLoaderRoute: typeof AuthenticatedOnboardedManageSettingsRouteImport
      parentRoute: typeof AuthenticatedOnboardedRoute
    }
    '/_authenticated/_onboarded/expenses/monthly-expenses/': {
      id: '/_authenticated/_onboarded/expenses/monthly-expenses/'
      path: '/'
      fullPath: '/expenses/monthly-expenses/'
      preLoaderRoute: typeof AuthenticatedOnboardedExpensesMonthlyExpensesIndexRouteImport
      parentRoute: typeof AuthenticatedOnboardedExpensesMonthlyExpensesRouteRoute
    }
    '/_authenticated/_onboarded/expenses/monthly-expenses/categories': {
      id: '/_authenticated/_onboarded/expenses/monthly-expenses/categories'
      path: '/categories'
      fullPath: '/expenses/monthly-expenses/categories'
      preLoaderRoute: typeof AuthenticatedOnboardedExpensesMonthlyExpensesCategoriesRouteImport
      parentRoute: typeof AuthenticatedOnboardedExpensesMonthlyExpensesRouteRoute
    }
    '/_authenticated/_onboarded/family/contacts/': {
      id: '/_authenticated/_onboarded/family/contacts/'
      path: '/family/contacts'
      fullPath: '/family/contacts/'
      preLoaderRoute: typeof AuthenticatedOnboardedFamilyContactsIndexRouteImport
      parentRoute: typeof AuthenticatedOnboardedRoute
    }
    '/_authenticated/_onboarded/family/contacts/$contactId': {
      id: '/_authenticated/_onboarded/family/contacts/$contactId'
      path: '/family/contacts/$contactId'
      fullPath: '/family/contacts/$contactId'
      preLoaderRoute: typeof AuthenticatedOnboardedFamilyContactsContactIdRouteImport
      parentRoute: typeof AuthenticatedOnboardedRoute
    }
    '/_authenticated/_onboarded/family/kids/': {
      id: '/_authenticated/_onboarded/family/kids/'
      path: '/family/kids'
      fullPath: '/family/kids/'
      preLoaderRoute: typeof AuthenticatedOnboardedFamilyKidsIndexRouteImport
      parentRoute: typeof AuthenticatedOnboardedRoute
    }
    '/_authenticated/_onboarded/family/kids/$profileId': {
      id: '/_authenticated/_onboarded/family/kids/$profileId'
      path: '/family/kids/$profileId'
      fullPath: '/family/kids/$profileId'
      preLoaderRoute: typeof AuthenticatedOnboardedFamilyKidsProfileIdRouteRouteImport
      parentRoute: typeof AuthenticatedOnboardedRoute
    }
    '/_authenticated/_onboarded/family/pets/': {
      id: '/_authenticated/_onboarded/family/pets/'
      path: '/family/pets'
      fullPath: '/family/pets/'
      preLoaderRoute: typeof AuthenticatedOnboardedFamilyPetsIndexRouteImport
      parentRoute: typeof AuthenticatedOnboardedRoute
    }
    '/_authenticated/_onboarded/family/pets/$profileId': {
      id: '/_authenticated/_onboarded/family/pets/$profileId'
      path: '/family/pets/$profileId'
      fullPath: '/family/pets/$profileId'
      preLoaderRoute: typeof AuthenticatedOnboardedFamilyPetsProfileIdRouteRouteImport
      parentRoute: typeof AuthenticatedOnboardedRoute
    }
    '/_authenticated/_onboarded/food/ingredients/': {
      id: '/_authenticated/_onboarded/food/ingredients/'
      path: '/'
      fullPath: '/food/ingredients/'
      preLoaderRoute: typeof AuthenticatedOnboardedFoodIngredientsIndexRouteImport
      parentRoute: typeof AuthenticatedOnboardedFoodIngredientsRouteRoute
    }
    '/_authenticated/_onboarded/food/ingredients/stores': {
      id: '/_authenticated/_onboarded/food/ingredients/stores'
      path: '/stores'
      fullPath: '/food/ingredients/stores'
      preLoaderRoute: typeof AuthenticatedOnboardedFoodIngredientsStoresRouteImport
      parentRoute: typeof AuthenticatedOnboardedFoodIngredientsRouteRoute
    }
    '/_authenticated/_onboarded/food/meal-plan/': {
      id: '/_authenticated/_onboarded/food/meal-plan/'
      path: '/food/meal-plan'
      fullPath: '/food/meal-plan/'
      preLoaderRoute: typeof AuthenticatedOnboardedFoodMealPlanIndexRouteImport
      parentRoute: typeof AuthenticatedOnboardedRoute
    }
    '/_authenticated/_onboarded/food/recipes/': {
      id: '/_authenticated/_onboarded/food/recipes/'
      path: '/food/recipes'
      fullPath: '/food/recipes/'
      preLoaderRoute: typeof AuthenticatedOnboardedFoodRecipesIndexRouteImport
      parentRoute: typeof AuthenticatedOnboardedRoute
    }
    '/_authenticated/_onboarded/food/recipes/$recipeId': {
      id: '/_authenticated/_onboarded/food/recipes/$recipeId'
      path: '/food/recipes/$recipeId'
      fullPath: '/food/recipes/$recipeId'
      preLoaderRoute: typeof AuthenticatedOnboardedFoodRecipesRecipeIdRouteRouteImport
      parentRoute: typeof AuthenticatedOnboardedRoute
    }
    '/_authenticated/_onboarded/food/recipes/new': {
      id: '/_authenticated/_onboarded/food/recipes/new'
      path: '/food/recipes/new'
      fullPath: '/food/recipes/new'
      preLoaderRoute: typeof AuthenticatedOnboardedFoodRecipesNewRouteImport
      parentRoute: typeof AuthenticatedOnboardedRoute
    }
    '/_authenticated/_onboarded/food/shopping-lists/': {
      id: '/_authenticated/_onboarded/food/shopping-lists/'
      path: '/'
      fullPath: '/food/shopping-lists/'
      preLoaderRoute: typeof AuthenticatedOnboardedFoodShoppingListsIndexRouteImport
      parentRoute: typeof AuthenticatedOnboardedFoodShoppingListsRouteRoute
    }
    '/_authenticated/_onboarded/food/shopping-lists/$listId': {
      id: '/_authenticated/_onboarded/food/shopping-lists/$listId'
      path: '/$listId'
      fullPath: '/food/shopping-lists/$listId'
      preLoaderRoute: typeof AuthenticatedOnboardedFoodShoppingListsListIdRouteImport
      parentRoute: typeof AuthenticatedOnboardedFoodShoppingListsRouteRoute
    }
    '/_authenticated/_onboarded/food/shopping-lists/import': {
      id: '/_authenticated/_onboarded/food/shopping-lists/import'
      path: '/import'
      fullPath: '/food/shopping-lists/import'
      preLoaderRoute: typeof AuthenticatedOnboardedFoodShoppingListsImportRouteImport
      parentRoute: typeof AuthenticatedOnboardedFoodShoppingListsRouteRoute
    }
    '/_authenticated/_onboarded/storage/items/': {
      id: '/_authenticated/_onboarded/storage/items/'
      path: '/storage/items'
      fullPath: '/storage/items/'
      preLoaderRoute: typeof AuthenticatedOnboardedStorageItemsIndexRouteImport
      parentRoute: typeof AuthenticatedOnboardedRoute
    }
    '/_authenticated/_onboarded/storage/locations/': {
      id: '/_authenticated/_onboarded/storage/locations/'
      path: '/storage/locations'
      fullPath: '/storage/locations/'
      preLoaderRoute: typeof AuthenticatedOnboardedStorageLocationsIndexRouteImport
      parentRoute: typeof AuthenticatedOnboardedRoute
    }
    '/_authenticated/_onboarded/storage/locations/$locationId': {
      id: '/_authenticated/_onboarded/storage/locations/$locationId'
      path: '/storage/locations/$locationId'
      fullPath: '/storage/locations/$locationId'
      preLoaderRoute: typeof AuthenticatedOnboardedStorageLocationsLocationIdRouteImport
      parentRoute: typeof AuthenticatedOnboardedRoute
    }
    '/_authenticated/_onboarded/family/kids/$profileId/': {
      id: '/_authenticated/_onboarded/family/kids/$profileId/'
      path: '/'
      fullPath: '/family/kids/$profileId/'
      preLoaderRoute: typeof AuthenticatedOnboardedFamilyKidsProfileIdIndexRouteImport
      parentRoute: typeof AuthenticatedOnboardedFamilyKidsProfileIdRouteRoute
    }
    '/_authenticated/_onboarded/family/kids/$profileId/dictionary': {
      id: '/_authenticated/_onboarded/family/kids/$profileId/dictionary'
      path: '/dictionary'
      fullPath: '/family/kids/$profileId/dictionary'
      preLoaderRoute: typeof AuthenticatedOnboardedFamilyKidsProfileIdDictionaryRouteImport
      parentRoute: typeof AuthenticatedOnboardedFamilyKidsProfileIdRouteRoute
    }
    '/_authenticated/_onboarded/family/kids/$profileId/general': {
      id: '/_authenticated/_onboarded/family/kids/$profileId/general'
      path: '/general'
      fullPath: '/family/kids/$profileId/general'
      preLoaderRoute: typeof AuthenticatedOnboardedFamilyKidsProfileIdGeneralRouteImport
      parentRoute: typeof AuthenticatedOnboardedFamilyKidsProfileIdRouteRoute
    }
    '/_authenticated/_onboarded/family/pets/$profileId/': {
      id: '/_authenticated/_onboarded/family/pets/$profileId/'
      path: '/'
      fullPath: '/family/pets/$profileId/'
      preLoaderRoute: typeof AuthenticatedOnboardedFamilyPetsProfileIdIndexRouteImport
      parentRoute: typeof AuthenticatedOnboardedFamilyPetsProfileIdRouteRoute
    }
    '/_authenticated/_onboarded/family/pets/$profileId/general': {
      id: '/_authenticated/_onboarded/family/pets/$profileId/general'
      path: '/general'
      fullPath: '/family/pets/$profileId/general'
      preLoaderRoute: typeof AuthenticatedOnboardedFamilyPetsProfileIdGeneralRouteImport
      parentRoute: typeof AuthenticatedOnboardedFamilyPetsProfileIdRouteRoute
    }
    '/_authenticated/_onboarded/food/recipes/$recipeId/': {
      id: '/_authenticated/_onboarded/food/recipes/$recipeId/'
      path: '/'
      fullPath: '/food/recipes/$recipeId/'
      preLoaderRoute: typeof AuthenticatedOnboardedFoodRecipesRecipeIdIndexRouteImport
      parentRoute: typeof AuthenticatedOnboardedFoodRecipesRecipeIdRouteRoute
    }
    '/_authenticated/_onboarded/food/recipes/$recipeId/edit': {
      id: '/_authenticated/_onboarded/food/recipes/$recipeId/edit'
      path: '/edit'
      fullPath: '/food/recipes/$recipeId/edit'
      preLoaderRoute: typeof AuthenticatedOnboardedFoodRecipesRecipeIdEditRouteImport
      parentRoute: typeof AuthenticatedOnboardedFoodRecipesRecipeIdRouteRoute
    }
  }
}

interface AuthenticatedOnboardingRouteRouteChildren {
  AuthenticatedOnboardingCreateHouseholdRoute: typeof AuthenticatedOnboardingCreateHouseholdRoute
  AuthenticatedOnboardingInviteMembersRoute: typeof AuthenticatedOnboardingInviteMembersRoute
  AuthenticatedOnboardingIndexRoute: typeof AuthenticatedOnboardingIndexRoute
}

const AuthenticatedOnboardingRouteRouteChildren: AuthenticatedOnboardingRouteRouteChildren =
  {
    AuthenticatedOnboardingCreateHouseholdRoute:
      AuthenticatedOnboardingCreateHouseholdRoute,
    AuthenticatedOnboardingInviteMembersRoute:
      AuthenticatedOnboardingInviteMembersRoute,
    AuthenticatedOnboardingIndexRoute: AuthenticatedOnboardingIndexRoute,
  }

const AuthenticatedOnboardingRouteRouteWithChildren =
  AuthenticatedOnboardingRouteRoute._addFileChildren(
    AuthenticatedOnboardingRouteRouteChildren,
  )

interface AuthenticatedOnboardedExpensesMonthlyExpensesRouteRouteChildren {
  AuthenticatedOnboardedExpensesMonthlyExpensesCategoriesRoute: typeof AuthenticatedOnboardedExpensesMonthlyExpensesCategoriesRoute
  AuthenticatedOnboardedExpensesMonthlyExpensesIndexRoute: typeof AuthenticatedOnboardedExpensesMonthlyExpensesIndexRoute
}

const AuthenticatedOnboardedExpensesMonthlyExpensesRouteRouteChildren: AuthenticatedOnboardedExpensesMonthlyExpensesRouteRouteChildren =
  {
    AuthenticatedOnboardedExpensesMonthlyExpensesCategoriesRoute:
      AuthenticatedOnboardedExpensesMonthlyExpensesCategoriesRoute,
    AuthenticatedOnboardedExpensesMonthlyExpensesIndexRoute:
      AuthenticatedOnboardedExpensesMonthlyExpensesIndexRoute,
  }

const AuthenticatedOnboardedExpensesMonthlyExpensesRouteRouteWithChildren =
  AuthenticatedOnboardedExpensesMonthlyExpensesRouteRoute._addFileChildren(
    AuthenticatedOnboardedExpensesMonthlyExpensesRouteRouteChildren,
  )

interface AuthenticatedOnboardedFoodIngredientsRouteRouteChildren {
  AuthenticatedOnboardedFoodIngredientsStoresRoute: typeof AuthenticatedOnboardedFoodIngredientsStoresRoute
  AuthenticatedOnboardedFoodIngredientsIndexRoute: typeof AuthenticatedOnboardedFoodIngredientsIndexRoute
}

const AuthenticatedOnboardedFoodIngredientsRouteRouteChildren: AuthenticatedOnboardedFoodIngredientsRouteRouteChildren =
  {
    AuthenticatedOnboardedFoodIngredientsStoresRoute:
      AuthenticatedOnboardedFoodIngredientsStoresRoute,
    AuthenticatedOnboardedFoodIngredientsIndexRoute:
      AuthenticatedOnboardedFoodIngredientsIndexRoute,
  }

const AuthenticatedOnboardedFoodIngredientsRouteRouteWithChildren =
  AuthenticatedOnboardedFoodIngredientsRouteRoute._addFileChildren(
    AuthenticatedOnboardedFoodIngredientsRouteRouteChildren,
  )

interface AuthenticatedOnboardedFoodShoppingListsRouteRouteChildren {
  AuthenticatedOnboardedFoodShoppingListsListIdRoute: typeof AuthenticatedOnboardedFoodShoppingListsListIdRoute
  AuthenticatedOnboardedFoodShoppingListsImportRoute: typeof AuthenticatedOnboardedFoodShoppingListsImportRoute
  AuthenticatedOnboardedFoodShoppingListsIndexRoute: typeof AuthenticatedOnboardedFoodShoppingListsIndexRoute
}

const AuthenticatedOnboardedFoodShoppingListsRouteRouteChildren: AuthenticatedOnboardedFoodShoppingListsRouteRouteChildren =
  {
    AuthenticatedOnboardedFoodShoppingListsListIdRoute:
      AuthenticatedOnboardedFoodShoppingListsListIdRoute,
    AuthenticatedOnboardedFoodShoppingListsImportRoute:
      AuthenticatedOnboardedFoodShoppingListsImportRoute,
    AuthenticatedOnboardedFoodShoppingListsIndexRoute:
      AuthenticatedOnboardedFoodShoppingListsIndexRoute,
  }

const AuthenticatedOnboardedFoodShoppingListsRouteRouteWithChildren =
  AuthenticatedOnboardedFoodShoppingListsRouteRoute._addFileChildren(
    AuthenticatedOnboardedFoodShoppingListsRouteRouteChildren,
  )

interface AuthenticatedOnboardedFamilyKidsProfileIdRouteRouteChildren {
  AuthenticatedOnboardedFamilyKidsProfileIdDictionaryRoute: typeof AuthenticatedOnboardedFamilyKidsProfileIdDictionaryRoute
  AuthenticatedOnboardedFamilyKidsProfileIdGeneralRoute: typeof AuthenticatedOnboardedFamilyKidsProfileIdGeneralRoute
  AuthenticatedOnboardedFamilyKidsProfileIdIndexRoute: typeof AuthenticatedOnboardedFamilyKidsProfileIdIndexRoute
}

const AuthenticatedOnboardedFamilyKidsProfileIdRouteRouteChildren: AuthenticatedOnboardedFamilyKidsProfileIdRouteRouteChildren =
  {
    AuthenticatedOnboardedFamilyKidsProfileIdDictionaryRoute:
      AuthenticatedOnboardedFamilyKidsProfileIdDictionaryRoute,
    AuthenticatedOnboardedFamilyKidsProfileIdGeneralRoute:
      AuthenticatedOnboardedFamilyKidsProfileIdGeneralRoute,
    AuthenticatedOnboardedFamilyKidsProfileIdIndexRoute:
      AuthenticatedOnboardedFamilyKidsProfileIdIndexRoute,
  }

const AuthenticatedOnboardedFamilyKidsProfileIdRouteRouteWithChildren =
  AuthenticatedOnboardedFamilyKidsProfileIdRouteRoute._addFileChildren(
    AuthenticatedOnboardedFamilyKidsProfileIdRouteRouteChildren,
  )

interface AuthenticatedOnboardedFamilyPetsProfileIdRouteRouteChildren {
  AuthenticatedOnboardedFamilyPetsProfileIdGeneralRoute: typeof AuthenticatedOnboardedFamilyPetsProfileIdGeneralRoute
  AuthenticatedOnboardedFamilyPetsProfileIdIndexRoute: typeof AuthenticatedOnboardedFamilyPetsProfileIdIndexRoute
}

const AuthenticatedOnboardedFamilyPetsProfileIdRouteRouteChildren: AuthenticatedOnboardedFamilyPetsProfileIdRouteRouteChildren =
  {
    AuthenticatedOnboardedFamilyPetsProfileIdGeneralRoute:
      AuthenticatedOnboardedFamilyPetsProfileIdGeneralRoute,
    AuthenticatedOnboardedFamilyPetsProfileIdIndexRoute:
      AuthenticatedOnboardedFamilyPetsProfileIdIndexRoute,
  }

const AuthenticatedOnboardedFamilyPetsProfileIdRouteRouteWithChildren =
  AuthenticatedOnboardedFamilyPetsProfileIdRouteRoute._addFileChildren(
    AuthenticatedOnboardedFamilyPetsProfileIdRouteRouteChildren,
  )

interface AuthenticatedOnboardedFoodRecipesRecipeIdRouteRouteChildren {
  AuthenticatedOnboardedFoodRecipesRecipeIdEditRoute: typeof AuthenticatedOnboardedFoodRecipesRecipeIdEditRoute
  AuthenticatedOnboardedFoodRecipesRecipeIdIndexRoute: typeof AuthenticatedOnboardedFoodRecipesRecipeIdIndexRoute
}

const AuthenticatedOnboardedFoodRecipesRecipeIdRouteRouteChildren: AuthenticatedOnboardedFoodRecipesRecipeIdRouteRouteChildren =
  {
    AuthenticatedOnboardedFoodRecipesRecipeIdEditRoute:
      AuthenticatedOnboardedFoodRecipesRecipeIdEditRoute,
    AuthenticatedOnboardedFoodRecipesRecipeIdIndexRoute:
      AuthenticatedOnboardedFoodRecipesRecipeIdIndexRoute,
  }

const AuthenticatedOnboardedFoodRecipesRecipeIdRouteRouteWithChildren =
  AuthenticatedOnboardedFoodRecipesRecipeIdRouteRoute._addFileChildren(
    AuthenticatedOnboardedFoodRecipesRecipeIdRouteRouteChildren,
  )

interface AuthenticatedOnboardedRouteChildren {
  AuthenticatedOnboardedGuestRoute: typeof AuthenticatedOnboardedGuestRoute
  AuthenticatedOnboardedUserProfileRoute: typeof AuthenticatedOnboardedUserProfileRoute
  AuthenticatedOnboardedIndexRoute: typeof AuthenticatedOnboardedIndexRoute
  AuthenticatedOnboardedExpensesMonthlyExpensesRouteRoute: typeof AuthenticatedOnboardedExpensesMonthlyExpensesRouteRouteWithChildren
  AuthenticatedOnboardedFoodIngredientsRouteRoute: typeof AuthenticatedOnboardedFoodIngredientsRouteRouteWithChildren
  AuthenticatedOnboardedFoodShoppingListsRouteRoute: typeof AuthenticatedOnboardedFoodShoppingListsRouteRouteWithChildren
  AuthenticatedOnboardedManageActivityRoute: typeof AuthenticatedOnboardedManageActivityRoute
  AuthenticatedOnboardedManageHouseholdMembersRoute: typeof AuthenticatedOnboardedManageHouseholdMembersRoute
  AuthenticatedOnboardedManageSettingsRoute: typeof AuthenticatedOnboardedManageSettingsRoute
  AuthenticatedOnboardedFamilyKidsProfileIdRouteRoute: typeof AuthenticatedOnboardedFamilyKidsProfileIdRouteRouteWithChildren
  AuthenticatedOnboardedFamilyPetsProfileIdRouteRoute: typeof AuthenticatedOnboardedFamilyPetsProfileIdRouteRouteWithChildren
  AuthenticatedOnboardedFoodRecipesRecipeIdRouteRoute: typeof AuthenticatedOnboardedFoodRecipesRecipeIdRouteRouteWithChildren
  AuthenticatedOnboardedFamilyContactsContactIdRoute: typeof AuthenticatedOnboardedFamilyContactsContactIdRoute
  AuthenticatedOnboardedFoodRecipesNewRoute: typeof AuthenticatedOnboardedFoodRecipesNewRoute
  AuthenticatedOnboardedStorageLocationsLocationIdRoute: typeof AuthenticatedOnboardedStorageLocationsLocationIdRoute
  AuthenticatedOnboardedFamilyContactsIndexRoute: typeof AuthenticatedOnboardedFamilyContactsIndexRoute
  AuthenticatedOnboardedFamilyKidsIndexRoute: typeof AuthenticatedOnboardedFamilyKidsIndexRoute
  AuthenticatedOnboardedFamilyPetsIndexRoute: typeof AuthenticatedOnboardedFamilyPetsIndexRoute
  AuthenticatedOnboardedFoodMealPlanIndexRoute: typeof AuthenticatedOnboardedFoodMealPlanIndexRoute
  AuthenticatedOnboardedFoodRecipesIndexRoute: typeof AuthenticatedOnboardedFoodRecipesIndexRoute
  AuthenticatedOnboardedStorageItemsIndexRoute: typeof AuthenticatedOnboardedStorageItemsIndexRoute
  AuthenticatedOnboardedStorageLocationsIndexRoute: typeof AuthenticatedOnboardedStorageLocationsIndexRoute
}

const AuthenticatedOnboardedRouteChildren: AuthenticatedOnboardedRouteChildren =
  {
    AuthenticatedOnboardedGuestRoute: AuthenticatedOnboardedGuestRoute,
    AuthenticatedOnboardedUserProfileRoute:
      AuthenticatedOnboardedUserProfileRoute,
    AuthenticatedOnboardedIndexRoute: AuthenticatedOnboardedIndexRoute,
    AuthenticatedOnboardedExpensesMonthlyExpensesRouteRoute:
      AuthenticatedOnboardedExpensesMonthlyExpensesRouteRouteWithChildren,
    AuthenticatedOnboardedFoodIngredientsRouteRoute:
      AuthenticatedOnboardedFoodIngredientsRouteRouteWithChildren,
    AuthenticatedOnboardedFoodShoppingListsRouteRoute:
      AuthenticatedOnboardedFoodShoppingListsRouteRouteWithChildren,
    AuthenticatedOnboardedManageActivityRoute:
      AuthenticatedOnboardedManageActivityRoute,
    AuthenticatedOnboardedManageHouseholdMembersRoute:
      AuthenticatedOnboardedManageHouseholdMembersRoute,
    AuthenticatedOnboardedManageSettingsRoute:
      AuthenticatedOnboardedManageSettingsRoute,
    AuthenticatedOnboardedFamilyKidsProfileIdRouteRoute:
      AuthenticatedOnboardedFamilyKidsProfileIdRouteRouteWithChildren,
    AuthenticatedOnboardedFamilyPetsProfileIdRouteRoute:
      AuthenticatedOnboardedFamilyPetsProfileIdRouteRouteWithChildren,
    AuthenticatedOnboardedFoodRecipesRecipeIdRouteRoute:
      AuthenticatedOnboardedFoodRecipesRecipeIdRouteRouteWithChildren,
    AuthenticatedOnboardedFamilyContactsContactIdRoute:
      AuthenticatedOnboardedFamilyContactsContactIdRoute,
    AuthenticatedOnboardedFoodRecipesNewRoute:
      AuthenticatedOnboardedFoodRecipesNewRoute,
    AuthenticatedOnboardedStorageLocationsLocationIdRoute:
      AuthenticatedOnboardedStorageLocationsLocationIdRoute,
    AuthenticatedOnboardedFamilyContactsIndexRoute:
      AuthenticatedOnboardedFamilyContactsIndexRoute,
    AuthenticatedOnboardedFamilyKidsIndexRoute:
      AuthenticatedOnboardedFamilyKidsIndexRoute,
    AuthenticatedOnboardedFamilyPetsIndexRoute:
      AuthenticatedOnboardedFamilyPetsIndexRoute,
    AuthenticatedOnboardedFoodMealPlanIndexRoute:
      AuthenticatedOnboardedFoodMealPlanIndexRoute,
    AuthenticatedOnboardedFoodRecipesIndexRoute:
      AuthenticatedOnboardedFoodRecipesIndexRoute,
    AuthenticatedOnboardedStorageItemsIndexRoute:
      AuthenticatedOnboardedStorageItemsIndexRoute,
    AuthenticatedOnboardedStorageLocationsIndexRoute:
      AuthenticatedOnboardedStorageLocationsIndexRoute,
  }

const AuthenticatedOnboardedRouteWithChildren =
  AuthenticatedOnboardedRoute._addFileChildren(
    AuthenticatedOnboardedRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedOnboardingRouteRoute: typeof AuthenticatedOnboardingRouteRouteWithChildren
  AuthenticatedOnboardedRoute: typeof AuthenticatedOnboardedRouteWithChildren
  AuthenticatedJoinHouseholdRoute: typeof AuthenticatedJoinHouseholdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedOnboardingRouteRoute:
    AuthenticatedOnboardingRouteRouteWithChildren,
  AuthenticatedOnboardedRoute: AuthenticatedOnboardedRouteWithChildren,
  AuthenticatedJoinHouseholdRoute: AuthenticatedJoinHouseholdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
