@url = http://localhost:5173

# @name login
POST {{url}}/auth/sign-in/email
content-type: application/json

{ "email": "ziga.krasovec@optifarm.net", "password": "Test1234!" }

###

# @name logout
POST {{url}}/auth/sign-out

###

GET {{url}}/households/my

###

GET {{url}}/expenses/6

###

POST {{url}}/expenses
content-type: application/json

{
  "name": "New name",
  "amount": 10.2
}

###

DELETE {{url}}/expenses/6