@url = http://localhost:5173

# @name login
POST {{url}}/auth/sign-in/email
content-type: application/json

{ "email": "ziga.krasovec@optifarm.net", "password": "Test1234!" }

###

# @name logout
POST {{url}}/auth/sign-out

###

GET {{url}}/households/my

###

GET {{url}}/households/2

###

POST {{url}}/households
content-type: application/json

{
  "name": "Our family"
}

###

DELETE {{url}}/households/9